apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespaces-stag-us-central-1-default
  namespace: default
spec:
  interval: 1m0s
  path: manifests/namespaces/stag-us-central-1/default
  retryInterval: 15s
  sourceRef:
    kind: GitRepository
    name: tanka-exporter-workflow
    namespace: flux-system
