name: Install Tanka
description: Install Tanka

inputs:
  version:
    description: |
      Version of Tanka to install.
    default: 0.27.1

runs:
  using: composite

  steps:
    - name: Restore cache
      id: restore
      uses: actions/cache/restore@v4
      with:
        path: ${{ github.workspace }}/bin
        key: tk-linux-amd64-${{ inputs.version }}

    - name: Fetch Github Release Asset
      id: fetch_asset
      if: steps.restore.outputs.cache-hit != 'true'
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: "grafana/tanka"
        version: "tags/v${{ inputs.version }}"
        file: "tk-linux-amd64"
        target: ${{ github.workspace }}/bin/tk

    - name: chmod
      id: chmod
      if: steps.fetch_asset.outcome == 'success'
      shell: sh
      run: |
        chmod +x ${{ github.workspace }}/bin/tk

    - name: Save to cache
      id: save
      if: steps.gunzip.outcome == 'success'
      uses: actions/cache/save@v4
      with:
        path: ${{ github.workspace }}/bin
        key: ${{ steps.restore.outputs.cache-primary-key }}

    - name: Add binary to path
      shell: sh
      run: |
        echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
